# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
