# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
    ]
