# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_secrets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secrets',
            old_name='secrets',
            new_name='secret',
        ),
    ]
