# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170427_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrets',
            name='like_by',
            field=models.ManyToManyField(related_name='like', to='first_app.Information'),
        ),
        migrations.AlterField(
            model_name='secrets',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='first_app.Information'),
        ),
    ]
