# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0005_remove_user_number'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='the_user', to='logreg.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
